name: Test Pull Request

on:
  pull_request:
    branches:
    - main

concurrency:
  # only one instance of test suite per PR at one time
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration Tests with Builders
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        builder: ["builder-1","builder-2"]
      fail-fast: false  # don't cancel all test jobs when one fails
    steps:
    - name: Run Integration Tests
      run: |
        if [[ ${{ matrix.builder }} == "builder-1" ]]; then
          echo "failing on builder-1"
          exit 1
        else
          echo "passing on ${{ matrix.builder }}"
          exit 0
        fi

  roundup:
    name: Integration Tests
    runs-on: ubuntu-22.04
    needs: integration
    steps:
    - run: |
        echo "Integration tests passed against all builders"
        exit 0
