name: Test Pull Request

on:
  pull_request:
    branches:
    - main

concurrency:
  # only one instance of test suite per PR at one time
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration Tests with Builders
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        builder: ["builder-1","builder-2"]
      fail-fast: false  # don't cancel all test jobs when one fails
    steps:
    - name: Run Integration Tests
      run: |
        echo "always passing"
        exit 0

  roundup:
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    name: Integration Tests
    needs: [integration]
    steps:
    - run: |
        result="${{ needs.integration.result }}"
        if [[ $result == "success"  ]]; then
          echo "Integration tests passed against all builders"
          exit 0
        else
          echo "Integration tests failed on one or more builders"
          exit 1
        fi
